
pullRequestOpened: >
  Thank you for raising your pull request.

  Please make sure you have followed @mazipan, and please push ⭐ button in this repository.

  I may add label `invalid` and close your PR, if doesn't see your account staring this repository. 🙏
