version = 1

[merge]
# Label to enable Kodiak to merge a PR.

# By default, Kodiak will only act on PRs that have this label. You can disable
# this requirement via `merge.require_automerge_label`.
automerge_label = "automerge" # default: "automerge"

# Require that the automerge label (`merge.automerge_label`) be set for Kodiak
# to merge a PR.
#
# When disabled, Kodiak will immediately attempt to merge any PR that passes all
# GitHub branch protection requirements.
require_automerge_label = true

[update]
always = true # default: false
ignored_usernames = ["dependabot", "snyk-bot"]

[approve]
auto_approve_usernames = ["ImgBotApp", "imgbot"]

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot", "snyk-bot"]

# https://kodiakhq.com/docs/recipes#better-merge-messages
[merge.message]

title = "pull_request_title" # default: "github_default"
body = "pull_request_body" # default: "github_default"
include_pr_number = true
include_coauthors = true
